### ISSUE TITLE
Cheatsheet for docker

### ISSUE THREAD

**Issue by dschier-wtd** [while-true-do/tldr#7]
As a contributor/user, I want to have a docker cheat sheet present with some examples and most commonly used commands.

**Comment by TheRojam** [comment]
I found some helpfull links, hopfully:
- https://hackernoon.com/docker-commands-the-ultimate-cheat-sheet-994ac78e2888
- https://github.com/wsargent/docker-cheat-sheet
- https://caylent.com/docker-commands-cheat-sheet/
- https://zeroturnaround.com/rebellabs/docker-commands-and-best-practices-cheat-sheet/
- https://linoxide.com/linux-how-to/docker-commands-cheat-sheet/

May you could use these as examples for your own

**Comment by dschier-wtd** [comment]
Cool, working on it.
